C     SONETO ALFANUMERICO
C     ------------------------------------------------------------------
C     RECONSTRUCAO HIPOTETICA. O PROGRAMA DE ERTHOS ALBINO DE SOUZA
C     (FORTRAN E PL/1, 1974) NAO SOBREVIVEU. ESTE E UM EXERCICIO EM
C     FORTRAN IV, NO ESTILO DA EPOCA, DE COMO ELE PODERIA TER SIDO:
C     APLICA A TABELA RECUPERADA DA PAGINA IMPRESSA (DECIFRACAO.MD).
C
C     ENTRADA  CARTOES DE 80 COLUNAS, UM VERSO POR CARTAO, EM
C              MAIUSCULAS SEM ACENTO, COMO NA PERFURADORA.
C     SAIDA    O VERSO CIFRADO, NA IMPRESSORA DE LINHA.
C     TABELA   CADA LETRA VIRA SEMPRE O MESMO SIMBOLO. K, W E Z NAO
C              OCORREM EM MALLARME E FICAM COMO ESTAO. O RESTO DO
C              CARTAO (ESPACO, PONTUACAO) PASSA SEM MUDAR.
C     ------------------------------------------------------------------
      INTEGER ALF(26), SIM(26), CARTAO(80), I, J
      DATA ALF /1HA,1HB,1HC,1HD,1HE,1HF,1HG,1HH,1HI,1HJ,1HK,1HL,1HM,
     1          1HN,1HO,1HP,1HQ,1HR,1HS,1HT,1HU,1HV,1HW,1HX,1HY,1HZ/
      DATA SIM /1HA,1H!,1H",1H:,1H),1H;,1H¬,1H',1H2,1H4,1HK,1H6,1H7,
     1          1H(,1H3,1H&,1H+,1H¢,1H>,1H-,1H1,1H=,1HW,1H?,1H|,1HZ/
C
   10 READ (5,100,END=99) CARTAO
      DO 30 I = 1, 80
      DO 20 J = 1, 26
      IF (CARTAO(I) .NE. ALF(J)) GO TO 20
      CARTAO(I) = SIM(J)
      GO TO 30
   20 CONTINUE
   30 CONTINUE
      WRITE (6,200) CARTAO
      GO TO 10
C
   99 STOP
  100 FORMAT (80A1)
  200 FORMAT (1X,80A1)
      END
